spring:
  datasource:
    url: jdbc:mysql://localhost:3306/handbook?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: password
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:/mapping/*.xml
  type-aliases-package: com.example.regionhandbook.model